language: php
dist: trusty
php:
  - "5.6"
  - "7.0"
  - "7.1"
  - hhvm
install:
  - composer install
before_script:
  - ./scripts/check.sh
script:
  - ./scripts/test.sh
after_success:
  - ./scripts/coverage.sh
